/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./resources/js/Pages/AboutSection.vue')['default']
    Badge: typeof import('./resources/js/Components/ui/badge/Badge.vue')['default']
    Button: typeof import('./resources/js/Components/ui/button/Button.vue')['default']
    copy: typeof import('./resources/js/Components/ProjectNotes copy.vue')['default']
    FooterSection: typeof import('./resources/js/Pages/FooterSection.vue')['default']
    HeroSection: typeof import('./resources/js/Pages/HeroSection.vue')['default']
    Home: typeof import('./resources/js/Pages/Home.vue')['default']
    InteractiveGridPattern: typeof import('./resources/js/Components/ui/interactive-grid-pattern/InteractiveGridPattern.vue')['default']
    Label: typeof import('./resources/js/Components/ui/label/Label.vue')['default']
    Layout: typeof import('./resources/js/Layouts/Layout.vue')['default']
    Login: typeof import('./resources/js/Pages/Auth/Login.vue')['default']
    NeuralBg: typeof import('./resources/js/Components/ui/bg-neural/NeuralBg.vue')['default']
    PaginationLinks: typeof import('./resources/js/Pages/PaginationLinks.vue')['default']
    ProjectCard: typeof import('./resources/js/Components/ProjectCard.vue')['default']
    ProjectCards: typeof import('./resou./resources/js/Components/ProjectCard.vue]
    ProjectNotes: typeof import('./resources/js/Components/ProjectNotes.vue')['default']
    ProjectSection: typeof import('./resources/js/Pages/ProjectSection.vue')['default']
    Register: typeof import('./resources/js/Pages/Auth/Register.vue')['default']
    ScrollToButton: typeof import('./resources/js/Components/ScrollToButton.vue')['default']
    ShaderToy: typeof import('./resources/js/Components/ui/shader-toy/ShaderToy.vue')['default']
    SilkBackground: typeof import('./resources/js/Components/ui/bg-silk/SilkBackground.vue')['default']
    SkillsSection: typeof import('./resources/js/Pages/SkillsSection.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
  }
}
